# Generated by Django 4.0.4 on 2022-06-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custAddress',
            field=models.CharField(default='', max_length=50, verbose_name='Direccion del Cliente'),
        ),
    ]
