# Generated by Django 4.0.4 on 2022-07-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_custaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodStock',
            field=models.IntegerField(default=0, verbose_name='Stock del Producto'),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('bolId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id de Boleta')),
                ('bolCustName', models.CharField(max_length=80, verbose_name='Nombre del Cliente')),
                ('bolProdName', models.CharField(max_length=80, verbose_name='Nombre del Producto')),
                ('bolProdPrice', models.IntegerField(verbose_name='Precio del Cliente')),
                ('bolCant', models.IntegerField(verbose_name='Cantidad del producto')),
                ('bolEnvio', models.IntegerField(verbose_name='Valor Envio')),
                ('bolTotal', models.IntegerField(verbose_name='Total de la Boleta')),
                ('bolCustRut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('bolProdId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
