# Generated by Django 4.0.4 on 2022-07-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_prodstock_boleta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Miembros',
            new_name='Miembro',
        ),
    ]
