# Generated by Django 4.0.4 on 2022-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_miembros_miembro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='bolCustName',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='bolCustRut',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='bolProdId',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='bolProdName',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='bolProdPrice',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='bolTotal',
            field=models.IntegerField(verbose_name='Total'),
        ),
    ]
