# Generated by Django 4.0.4 on 2022-07-14 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_boleta_boldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bolDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
    ]
