# Generated by Django 4.0.4 on 2022-07-14 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_boleta_boldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bolDate',
            field=models.DateField(default=datetime.date(2022, 7, 14), verbose_name='Fecha'),
        ),
    ]
