# Generated by Django 4.0.4 on 2022-07-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_boleta_boldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bolDate',
            field=models.DateField(default='14-07-2022', verbose_name='Fecha'),
        ),
    ]
