# Generated by Django 4.0.4 on 2022-07-14 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_boleta_boldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bolDate',
            field=models.DateField(default=datetime.datetime(2022, 7, 14, 21, 18, 54, 746491, tzinfo=utc), verbose_name='Fecha'),
        ),
    ]
