# Generated by Django 4.0.4 on 2022-07-14 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_boleta_boldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bolDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
