# Generated by Django 4.0.4 on 2022-07-15 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_boleta_boldate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='bolDate',
            new_name='bolDateC',
        ),
        migrations.AddField(
            model_name='boleta',
            name='bolDateE',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
