# Generated by Django 4.0.4 on 2022-07-15 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_boldate_boleta_boldatec_boleta_boldatee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bolDateC',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Compra'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='bolDateE',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Entrega'),
        ),
    ]
