# Generated by Django 4.0.4 on 2022-07-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_boleta_bolcant_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
