# Generated by Django 4.0.4 on 2022-07-15 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_boleta_bolcliid_customer_custuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bolCliId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
